server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: srb-service-oss # 服务名
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
        namespace: public            # 命名空间（默认public，无需修改）
        group: DEFAULT_GROUP         # 分组（默认）
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5tDEBi8uzT6tuxVzHkP7
    keySecret: icSDxG8ZJb8B15pA1FuotkrFk26Nz5
    bucketName: zhouhui-srb

logging:
  level:
    com.alibaba.nacos: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG