server:
  port: 8220 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: srb-test-nacos # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址


